name: Go

on:
  push:
    branches: [ libevm ]
  pull_request:
    branches: [ libevm ]
  workflow_dispatch:

jobs:
  go_test_short:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
          cache: false
      - name: Run tests
        run: | # Upstream flakes are race conditions exacerbated by concurrent tests
          FLAKY_REGEX='go-ethereum/(eth|eth/tracers/logger|accounts/keystore|eth/downloader|miner|ethclient|ethclient/gethclient|eth/catalyst)$';
          go list ./... | grep -P "${FLAKY_REGEX}" | xargs -n 1 go test -short;
          go test -short $(go list ./... | grep -Pv "${FLAKY_REGEX}");
