name: Go

on:
  # DO NOT MERGE: disabled while developing auto-renaming
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  go_test_short:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.4
      - name: Run tests
        run: | # Upstream flakes are race conditions exacerbated by concurrent tests
          FLAKY_REGEX='go-ethereum/(eth|eth/tracers/js|eth/tracers/logger|accounts/abi/bind|accounts/keystore|eth/downloader|miner|ethclient|ethclient/gethclient|eth/catalyst)$';
          go list ./... | grep -P "${FLAKY_REGEX}" | xargs -n 1 go test -short;
          go test -short $(go list ./... | grep -Pv "${FLAKY_REGEX}");
