name: Go

on:
  push:
    branches: [ libevm ]
  pull_request:
    branches: [ libevm ]
  workflow_dispatch:

jobs:
  go_test_short:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4
      - name: Run tests
        run: | # Upstream flakes are race conditions exacerbated by concurrent tests
          FLAKY_REGEX='go-ethereum/(eth|accounts/keystore|eth/downloader|miner)$';
          go test -short $(go list ./... | grep -Pv "${FLAKY_REGEX}");
          go list ./... | grep -P "${FLAKY_REGEX}" | xargs -n 1 go test -short;
