name: libevm delta

on:
  push:
    branches: [ libevm ]
  pull_request:
    branches: [ libevm ]
  workflow_dispatch:

jobs:
  diffs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # everything
          fetch-tags: true
      - name: Diff libevm-base..libevm
        run: |
          git checkout libevm --;
          git diff --diff-filter=a --word-diff --unified=0 libevm-base..libevm \
            ':(exclude).golangci.yml' \
            ':(exclude).github/**';

      - name: Diff libevm-base..${{ github.ref_name }}
        run: |
          git checkout ${{ github.ref }} --;
          git diff --diff-filter=a --word-diff --unified=0 libevm-base..${{ github.ref }} \
            ':(exclude).golangci.yml' \
            ':(exclude).github/**';
