name: libevm delta

on:
  push:
    branches: [ libevm ]
  pull_request:
    branches: [ libevm ]
  workflow_dispatch:

jobs:
  diffs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # everything
          fetch-tags: true
      - name: Diff libevm-base..libevm
        run: |
          .github/workflows/diff_from_libevm-base.sh libevm
      - name: Diff libevm-base..${{ github.sha }}
        run: |
          .github/workflows/diff_from_libevm-base.sh ${{ github.sha }}
