name: libevm delta

on:
  push:
    branches: [ libevm ]
  pull_request:
    branches: [ libevm ]
  workflow_dispatch:

jobs:
  diffs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Diff libevm-base..{github.ref_name}
        run: |
          .github/workflows/diff_from_libevm-base.sh ${{ github.ref_name }}
      - name: Diff libevm-base..libevm
        run: |
          .github/workflows/diff_from_libevm-base.sh libevm
