name: libevm delta

on:
  push:
    branches: [ libevm ]
  pull_request:
    branches: [ libevm ]
  workflow_dispatch:

jobs:
  diffs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # everything
          fetch-tags: true
      
      - name: git diff libevm-base
        run: |
          git diff --diff-filter=a --word-diff --unified=0 libevm-base \
            ':(exclude).golangci.yml' \
            ':(exclude).github/**';
      
      - name: git diff libevm-base..libevm
        run: |
          git checkout libevm --;
          git diff --diff-filter=a --word-diff --unified=0 libevm-base..libevm \
            ':(exclude).golangci.yml' \
            ':(exclude).github/**';

