name: Rename Go module

on:
  push:
    branches: [ libevm ]
  pull_request: # DO NOT MERGE WITH ANYTHING OTHER THAN push
    branches: [ libevm ]
  workflow_dispatch:

jobs:
  rename-module:
    strategy:
      matrix:
        source_commit: ["2bd6bd01d2e8561dd7fc21b631f4a34ac16627a1"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # everything
          fetch-tags: true

      - name: Check out source commit
        run: git checkout ${{ matrix.source_commit }}

      - name: Globally update module name
        run: |
          go mod edit -module github.com/ava-labs/go-ethereum;
          find . -iname '*.go' | xargs sed -i -E \
            's|^((import)?\s.*?"github\.com/)ethereum/go-ethereum|\1ava-labs/go-ethereum|';
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.4

      - name: Smoke test by `go build ./...`
        run: | # `go list` just demonstrates the updated module name
          go list .;
          go build ./...

      - name: Commit to "auto-rename-module-${{ matrix.source_commit }}" branch
        uses: devops-infra/action-commit-push@8bc2ff9f9de7aa2a7581fc7e5b6401c04cab54c7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: "auto-rename-module-${{ matrix.source_commit }}"
          force: true
          commit_prefix: "[AUTO] rename Go module + update internal import paths"
